/*
 * pdf.js — one-click client-side PDF generation with jsPDF (bundled, vendor/).
 *
 * Part of Shubharambham Horoscope (AGPL-3.0). See README.md ("PDF and printing") and
 * Decisions.md #7. The document is built directly with jsPDF primitives — the single
 * bundled dependency — and the SVG charts are rasterised via an offscreen canvas so no
 * second library (html2canvas / svg2pdf) is needed. The on-screen "back to home" link is
 * absent from the PDF; the footer is kept on every page.
 */
(function (global) {
  "use strict";

  var MARGIN = 40;
  var PAGE_W = 595.28; // A4 portrait, pt
  var PAGE_H = 841.89;
  var FOOTER = "Generated by shubharambham.com/horoscope";
  var FOOTER_URL = "https://shubharambham.com/horoscope";

  // Rasterise a self-contained SVG string to a PNG data URL (async).
  function svgToPng(svgString, px) {
    return new Promise(function (resolve, reject) {
      var sized = svgString.replace("<svg ",
        '<svg width="' + px + '" height="' + px + '" ');
      var url = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(sized);
      var img = new Image();
      img.onload = function () {
        var canvas = document.createElement("canvas");
        canvas.width = px; canvas.height = px;
        var ctx = canvas.getContext("2d");
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, px, px);
        ctx.drawImage(img, 0, 0, px, px);
        try { resolve(canvas.toDataURL("image/png")); }
        catch (e) { reject(e); }
      };
      img.onerror = function () { reject(new Error("chart could not be rendered")); };
      img.src = url;
    });
  }

  function pad2(n) { return (n < 10 ? "0" : "") + n; }
  var MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct",
    "Nov", "Dec"];
  function fmtDate(d) {
    return pad2(d.getUTCDate()) + " " + MONTHS[d.getUTCMonth()] + " " + d.getUTCFullYear();
  }
  function fmtPos(g) {
    return g.deg + " " + g.signAbbr + " " + pad2(g.min) + "' " + pad2(g.sec) + '"';
  }

  function generate(model) {
    var jsPDF = global.jspdf.jsPDF;
    var doc = new jsPDF({ unit: "pt", format: "a4", orientation: "portrait" });
    var y = MARGIN;

    function ensure(space) {
      if (y + space > PAGE_H - MARGIN - 20) { doc.addPage(); y = MARGIN; }
    }

    // --- Title & birth summary ---
    var name = model.person.Name;
    doc.setFont("courier", "bold").setFontSize(18).setTextColor(30);
    doc.text(name ? name + "'s Horoscope" : "Horoscope", MARGIN, y);
    y += 22;

    var c = global.Common.parseLocalIso(model.person.DateTime);
    var timeStr = pad2(c.hour) + ":" + pad2(c.minute) + (c.second ? ":" + pad2(c.second) : "");
    var line1 = (model.person.Gender ? model.person.Gender + "  ·  " : "") +
      "Born " + pad2(c.day) + " " + MONTHS[c.month - 1] + " " + c.year + " at " + timeStr;
    var line2 = model.place.city + ", " + model.place.region +
      "  ·  " + model.place.lat.toFixed(4) + "°, " + model.place.long.toFixed(4) + "°  ·  " +
      model.place.tz;
    doc.setFont("courier", "normal").setFontSize(10).setTextColor(90);
    doc.text(line1, MARGIN, y); y += 14;
    doc.text(line2, MARGIN, y); y += 22;

    // --- Computed values ---
    var g = model.chart.grahas, a = model.chart.ascendant;
    var SIGN = global.Jyotish.SIGN_NAME;
    var values = [
      ["Tithi", model.tithi.displayFull],
      ["Nakshatra", g.Moon.nakshatra + " (pada " + g.Moon.pada + ")"],
      ["Sun — Vedic (sidereal)", g.Sun.signName],
      ["Sun — Western (tropical)", SIGN[model.westernSign]],
      ["Moon sign", g.Moon.signName + " · " + g.Moon.nakshatra + " pada " + g.Moon.pada],
      ["Lagna (ascendant)", a.signName + " " + fmtPos(a)]
    ];
    doc.setDrawColor(210).setLineWidth(0.5);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y); y += 16;
    doc.setFontSize(10);
    values.forEach(function (row) {
      ensure(16);
      doc.setFont("courier", "bold").setTextColor(60);
      doc.text(row[0] + ":", MARGIN, y);
      doc.setFont("courier", "normal").setTextColor(30);
      doc.text(String(row[1]), MARGIN + 150, y);
      y += 16;
    });
    y += 8;

    // --- Charts (rasterised from the currently-selected format) ---
    var asc = model.chart.ascendant;
    function placementsFor(div) {
      var out = []; for (var i = 0; i < 12; i++) out.push([]);
      model.chart.order.forEach(function (nm) {
        var gr = model.chart.grahas[nm];
        // gr.label parenthesises retrograde grahas, e.g. "(Ju)".
        out[div === "d9" ? gr.navamsaSign : gr.sign].push(gr.label || gr.abbr);
      });
      return out;
    }
    var d1svg = global.Charts.render(model.formatKey, placementsFor("d1"), asc.sign, { title: "D1" });
    var d9svg = global.Charts.render(model.formatKey, placementsFor("d9"), asc.navamsaSign, { title: "D9" });

    return Promise.all([svgToPng(d1svg, 640), svgToPng(d9svg, 640)]).then(function (imgs) {
      ensure(250);
      var chartW = (PAGE_W - 2 * MARGIN - 20) / 2;
      doc.setFont("courier", "bold").setFontSize(11).setTextColor(60);
      doc.text("Charts (" + chartLabel(model.formatKey) + ")", MARGIN, y);
      y += 12;
      var top = y;
      doc.addImage(imgs[0], "PNG", MARGIN, top, chartW, chartW);
      doc.addImage(imgs[1], "PNG", MARGIN + chartW + 20, top, chartW, chartW);
      doc.setFont("courier", "normal").setFontSize(9).setTextColor(110);
      doc.text("D1 · Rasi", MARGIN + chartW / 2, top + chartW + 12, { align: "center" });
      doc.text("D9 · Navamsa", MARGIN + chartW + 20 + chartW / 2, top + chartW + 12,
        { align: "center" });
      y = top + chartW + 28;

      // --- Planetary table ---
      ensure(40);
      doc.setFont("courier", "bold").setFontSize(11).setTextColor(60);
      doc.text("Planetary positions", MARGIN, y); y += 16;
      var cols = [
        { x: MARGIN, w: 70, t: "Planet" },
        { x: MARGIN + 70, w: 95, t: "Position" },
        { x: MARGIN + 165, w: 130, t: "Nakshatra (Pada)" },
        { x: MARGIN + 295, w: 45, t: "Rasi" },
        { x: MARGIN + 340, w: 55, t: "Navamsa" },
        { x: MARGIN + 395, w: 120, t: "Karaka" }
      ];
      doc.setFontSize(9).setTextColor(90);
      cols.forEach(function (col) { doc.text(col.t, col.x, y); });
      y += 4;
      doc.setDrawColor(210); doc.line(MARGIN, y, PAGE_W - MARGIN, y); y += 12;
      doc.setFont("courier", "normal").setTextColor(30);
      model.chart.order.forEach(function (nm) {
        ensure(16);
        var gr = model.chart.grahas[nm];
        var k = model.karakas[nm];
        var cells = [
          nm + " " + gr.label,
          fmtPos(gr),
          gr.nakshatra + " " + gr.pada,
          gr.signAbbr,
          gr.navamsaAbbr,
          k ? k.abbr + " " + k.name : "—"
        ];
        cells.forEach(function (txt, i) { doc.text(String(txt), cols[i].x, y); });
        y += 15;
      });
      y += 10;

      // --- Vimshottari dasha ---
      ensure(30);
      doc.setFont("courier", "bold").setFontSize(11).setTextColor(60);
      doc.text("Vimshottari Dasha", MARGIN, y); y += 16;
      model.dasha.mahadashas.forEach(function (md) {
        ensure(18);
        doc.setFont("courier", "bold").setFontSize(10).setTextColor(40);
        doc.text(md.lord + "   " + fmtDate(md.start) + " – " + fmtDate(md.end) +
          "   (" + md.years + " yrs)", MARGIN, y);
        y += 14;
        doc.setFont("courier", "normal").setFontSize(9).setTextColor(70);
        md.antars.forEach(function (ad) {
          ensure(13);
          doc.text(ad.lord + "  —  " + fmtDate(ad.start) + " – " + fmtDate(ad.end),
            MARGIN + 18, y);
          y += 12;
        });
        y += 6;
      });

      addFooters(doc);
      return doc;
    });
  }

  function chartLabel(key) {
    return key === "north" ? "North Indian" : key === "east" ? "East Indian" : "South Indian";
  }

  function addFooters(doc) {
    var pages = doc.internal.getNumberOfPages();
    for (var i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setDrawColor(220).setLineWidth(0.5);
      doc.line(MARGIN, PAGE_H - MARGIN, PAGE_W - MARGIN, PAGE_H - MARGIN);
      doc.setFont("courier", "normal").setFontSize(8).setTextColor(120);
      doc.textWithLink(FOOTER, MARGIN, PAGE_H - MARGIN + 12, { url: FOOTER_URL });
      doc.text("Page " + i + " of " + pages, PAGE_W - MARGIN, PAGE_H - MARGIN + 12,
        { align: "right" });
    }
  }

  global.PDF = { generate: generate };
})(typeof window !== "undefined" ? window : globalThis);
